"""Author: Nang Seng Khan
   Date: 10/05/2020
   link: https://github.com/NANGSENGKHAN/cp1404practicals
"""

BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        text: 'Clear'
    TextInput:
        id: input_name
        text: ''
    Button:
        text: 'Greet'
        on_press: app.handle_greet()
    Label:
        id: output_label
        text: 'Hello '
        color: (1, 1, 0, 1)
