BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        Button:
            text: 'Clear'
        TextInput:
            id: input_name
            text: ''
            size_hint_x: 3
    BoxLayout:
        orientation: 'horizontal'
        Button:
            text: 'Greet'
            on_press: app.handle_greet()
        Label:
            id: output_label
            size_hint_x: 3
            text: 'Hello '
            color: (1, 1, 0, 1)


